// client/src/app/modules/items/components/item-detail/item-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-item-detail',
  templateUrl: './item-detail.component.html',
  styleUrls: ['./item-detail.component.sass']
})
export class ItemDetailComponent implements OnInit {

  constructor(private route: ActivatedRoute) { }

  ngOnInit(): void {
    // alert(this.route.snapshot.params.id)
  }

}

<div class="item-detail-container p-4">
    <div class="item-detail-container-column left">
        <figure class="item-img">
            <img
                src="https://http2.mlstatic.com/D_NQ_NP_805950-MCO40352919808_012020-O.webp"
                class="product-item-img__image"
                alt="Celular iPhone 11 128gb Nuevo 100% Original Y Sellada ">
        </figure>
        <div class="specs">
            <h3 class="specs-title">Descripción del producto</h3>
            <p class="specs-content">
                CONTENIDO DE LA CAJA:

                -IPHONE
                -CABLE LIGHTNING A USB
                -DOCUMENTACIÓN
        
        
                -Cuerpo:
                Dimensiones: 146.7 x 71.5 x 7.4 mm (5.78 x 2.81 x 0.29 in)
                Peso: 164gr
                Material: Glass front (Gorilla Glass), glass back (Gorilla Glass), aluminum frame
                Apple Pay (Visa, MasterCard, AMEX certified)
            </p>
        </div>
    </div>
    <div class="item-detail-container-column short-description">
        <div class="short-description-title">
            <div class="secodary">
                <span class="ui-pdp-subtitle">Nuevo  |  10 vendidos</span>
            </div>
            <h3 class="principal">Celular Apple iPhone 12 128gb</h3>
        </div>
        <div class="short-description-price">
            <h1>$ 100.000.00</h1>
        </div>
        <div class="short-description-btns">
            <button
                class="ml-btn-primary mb-1"
                type="button">
                Comprar
            </button>
            <button
                class="ml-btn-secondary"
                type="button">
                Agregar al carrito
            </button>
        </div>
    </div>
</div>

// frontend-react/src/modules/items/item-detail/item-detail.js
import React, { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useParams } from "react-router-dom";
import currencyFormat from '../../../utils/format';
import { fetchProductDetail, selectProduct, selectWorking } from '../store/itemsSlice';
import './item-detail.sass';

export const ItemDetail = () => {
  const dispatch = useDispatch();
  const working = useSelector(selectWorking);
  const item = useSelector(selectProduct)
  let { id } = useParams();
  useEffect(() => dispatch(fetchProductDetail(id)), [dispatch, id]);
  useEffect(() => {
    document.title = item && item.hasOwnProperty('title') ? item.title : '';
  }, [item]);

  return working ? <Loading /> : item ? <Detail item={item} /> : <Empty />
}

const Detail = ({ item }) => {
  return (
    <div className="item-detail-container p-4">
      <div className="item-detail-container-column left">
        <figure className="item-img">
          <img
            src={item.picture}
            className="product-item-img__image"
            alt={item.title} />
        </figure>
        <Buttons className="short-description-btns mobile" />
        <div className="specs">
          <h3 className="specs-title">Descripción del producto</h3>
          <p className="specs-content">{item.description}</p>
        </div>
      </div>
      <div className="item-detail-container-column short-description">
        <div className="short-description-title">
          <div className="secodary">
            <span className="ui-pdp-subtitle">
              {item.condition} | {item.sold_quantity} vendidos
            </span>
          </div>
          <h3 className="principal">{item.title}</h3>
        </div>
        <div className="short-description-price">
          <h1>
            {/* {{ item.price.amount | currency:item.price.amount.currency }} */}
            {currencyFormat(item.price.amount)}
          </h1>
        </div>
        <Buttons className="short-description-btns desktop" />
      </div>
    </div >
  )
}

const Loading = () => (
  <div className="item-detail-container p-4">
    {[1, 2, 3, 4].map((number) =>
      <div key={number.toString()} className={`card-loader card-loader-item-${number}`}></div>
    )}
  </div>
)

const Empty = () => <div className="item-detail-container p-4">Producto no encontrado</div>

const Buttons = ({ className }) => (
  <div className={className}>
    <button
      className="ml-btn-primary mb-1"
      type="button">
      Comprar
    </button>
    <button
      className="ml-btn-secondary"
      type="button">
      Agregar al carrito
    </button>
  </div>
);

export default ItemDetail
