// frontend-react/src/modules/items/item-detail/item-detail.js
import React, { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useParams } from "react-router-dom";
import currencyFormat from '../../../utils/format';
import { fetchProductDetail, selectProduct, selectWorking } from '../store/itemsSlice';
import './item-detail.sass';

export const ItemDetail = () => {
  const dispatch = useDispatch();
  const working = useSelector(selectWorking);
  const item = useSelector(selectProduct)
  let { id } = useParams();
  useEffect(() => dispatch(fetchProductDetail(id)), [dispatch, id]);
  useEffect(() => {
    document.title = item && item.hasOwnProperty('title') ? item.title : '';
  }, [item]);

  return working ? <Loading /> : item ? <Detail item={item} /> : <Empty />
}

const Detail = ({ item }) => {
  return (
    <div className="item-detail-container p-4">
      <div className="item-detail-container-column left">
        <figure className="item-img">
          <img
            src={item.picture}
            className="product-item-img__image"
            alt={item.title} />
        </figure>
        <Buttons className="short-description-btns mobile" />
        <div className="specs">
          <h3 className="specs-title">Descripción del producto</h3>
          <p className="specs-content">{item.description}</p>
        </div>
      </div>
      <div className="item-detail-container-column short-description">
        <div className="short-description-title">
          <div className="secodary">
            <span className="ui-pdp-subtitle">
              {item.condition} | {item.sold_quantity} vendidos
            </span>
          </div>
          <h3 className="principal">{item.title}</h3>
        </div>
        <div className="short-description-price">
          <h1>
            {/* {{ item.price.amount | currency:item.price.amount.currency }} */}
            {currencyFormat(item.price.amount)}
          </h1>
        </div>
        <Buttons className="short-description-btns desktop" />
      </div>
    </div >
  )
}

const Loading = () => (
  <div className="item-detail-container p-4">
    {[1, 2, 3, 4].map((number) =>
      <div key={number.toString()} className={`card-loader card-loader-item-${number}`}></div>
    )}
  </div>
)

const Empty = () => <div className="item-detail-container p-4">Producto no encontrado</div>

const Buttons = ({ className }) => (
  <div className={className}>
    <button
      className="ml-btn-primary mb-1"
      type="button">
      Comprar
    </button>
    <button
      className="ml-btn-secondary"
      type="button">
      Agregar al carrito
    </button>
  </div>
);

export default ItemDetail

// frontend/src/app/modules/items/components/item-detail/item-detail.component.ts
import { filter } from 'rxjs/operators';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { ItemsI } from '../../entities/items.entity';
import { ItemsFacade } from './../../items.facade';
import { Meta, Title } from '@angular/platform-browser';

@Component({
  selector: 'app-item-detail',
  templateUrl: './item-detail.component.html',
  styleUrls: ['./item-detail.component.sass'],
})
export class ItemDetailComponent implements OnInit, OnDestroy {
  constructor(
    private route: ActivatedRoute,
    private facade: ItemsFacade,
    private meta: Meta,
    private title: Title
  ) {}

  ngOnInit(): void {
    this.facade.fetchProductDetail(this.route.snapshot.params.id);
    this.product$.pipe(filter((item) => !!item)).subscribe((item) => {
      // Para ñadir el título de la página
      this.title.setTitle(item.title);
      // Añadir el tag de la info de la página
      this.meta.addTag({
        name: 'description',
        content: item.description,
      });
    });
  }

  ngOnDestroy(): void {
    // Quitar el tag "description" antes de ir a otra página, para que rastree correctamente la información
    this.meta.removeTag(`name=\'description\'`);
  }

  get product$(): Observable<ItemsI> {
    return this.facade.product$;
  }

  get working$(): Observable<boolean> {
    return this.facade.working$;
  }
}

<div class="item-detail-container p-4">
    <ng-container *ngIf="(working$ | async); else !!(product$ | async) ? content : empty">
        <ng-container *ngFor="let i of [1,2,3]">
            <div class="card-loader card-loader-item-{{ i }}"></div>
        </ng-container>
    </ng-container>
    <ng-template #content>
        <ng-container *ngIf="(product$ | async) as item">
            <div class="item-detail-container-column left">
                <figure class="item-img">
                    <img
                        [src]="item.picture"
                        class="product-item-img__image"
                        [alt]="item.title">
                </figure>
                <div class="specs">
                    <h3 class="specs-title">Descripción del producto</h3>
                    <p class="specs-content">{{ item.description }}</p>
                </div>
            </div>
            <div class="item-detail-container-column short-description">
                <div class="short-description-title">
                    <div class="secodary">
                        <span class="ui-pdp-subtitle">
                            {{ item.condition }}  |  {{ item.sold_quantity }} vendidos
                        </span>
                    </div>
                    <h3 class="principal">{{ item.title | titlecase }}</h3>
                </div>
                <div class="short-description-price">
                    <h1>
                        {{ item.price.amount | currency:item.price.amount.currency }}
                    </h1>
                </div>
                <div class="short-description-btns">
                    <button
                        class="ml-btn-primary mb-1"
                        type="button">
                        Comprar
                    </button>
                    <button
                        class="ml-btn-secondary"
                        type="button">
                        Agregar al carrito
                    </button>
                </div>
            </div>
        </ng-container>
    </ng-template>
    <ng-template #empty>Producto no encontrado</ng-template>
</div>
