// frontend/src/app/modules/layout/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import {
  AbstractControl,
  FormBuilder,
  FormGroup,
  Validators,
} from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.sass'],
})
export class HeaderComponent implements OnInit {
  public formG: FormGroup;
  constructor(
    private router: Router,
    private formBuilder: FormBuilder,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.formG = this.formBuilder.group({
      searchControl: [null, [Validators.required]],
    });
    this.route.queryParams
      .pipe(filter(({ search }) => !!search))
      .subscribe(({ search }) => this.searchControl.patchValue(search));
  }

  public search(): void {
    document.getElementById('nav-search-input').blur();
    this.router.navigate(['/items'], {
      queryParams: { search: this.searchControl.value },
    });
  }

  get searchControl(): AbstractControl {
    return this.formG.get('searchControl');
  }
}

<header
    role="banner"
    class="ml-header-container py-1">
    <nav class="navbar container">
        <a
            class="navbar-brand mr-2"
            [routerLink]="['/items']">
            <!-- <img
                src="https://http2.mlstatic.com/frontend-assets/ui-navigation/5.12.0/mercadolibre/logo__large_plus@2x.png"
                src="https://http2.mlstatic.com/frontend-assets/ui-navigation/5.12.0/mercadolibre/logo__small@2x.png"
                alt="Logo"> -->
        </a>
        <div class="navbar-search">
            <form [formGroup]="formG" (ngSubmit)="search()">
                <input
                    [formControl]="searchControl"
                    id="nav-search-input"
                    class="nav-search-input"
                    type="search"
                    placeholder="Nunca dejes de buscar"
                    type="text"
                    aria-label="Search">
                <button
                    class="nav-search-btn"
                    [disabled]="searchControl.invalid"
                    type="submit">
                    <img
                        src="./assets/img/search.svg"
                        alt="buscar">
                </button>
            </form>
        </div>
    </nav>
</header>

// frontend-react/src/modules/layout/header/Header.js
import React from 'react'
import './header.sass'
import searchImg from '../../../assets/img/search.svg';

export const Header = () => {
    return (
        <header
            role="banner"
            className="ml-header-container py-1">
            <nav className="navbar container">
                <a className="navbar-brand mr-2"></a>
                <div className="navbar-search">
                    <form>
                        <input
                            id="nav-search-input"
                            className="nav-search-input"
                            type="search"
                            placeholder="Nunca dejes de buscar"
                            type="text"
                            aria-label="Search" />
                        <button
                            className="nav-search-btn"
                            type="submit">
                            <img
                                src={searchImg}
                                alt="buscar" />
                        </button>
                    </form>
                </div>
            </nav>
        </header >
    );
}

export default Header
