// frontend-react/src/modules/items/item-list/item-list.js
import { bindActionCreators } from '@reduxjs/toolkit';
import React from 'react';
import { connect } from 'react-redux';
import { Link } from "react-router-dom";
import trackImg from '../../../assets/img/track.svg';
import currencyFormat from '../../../utils/format';
import { fetchSearchProducts, selectItems, selectWorking } from '../store/itemsSlice';
import './item-list.sass';

const Loading = () => [1, 2, 3, 4].map((number) =>
  <div key={number.toString()} className="card-loader card-loader-item-1"></div>
)

const DeliveryIcon = () => (
  <span className="delivery-icon">
    <img
      src={trackImg}
      alt="Envio" />
  </span>
)

class Itemlist extends React.Component {

  componentDidMount() {
    const query = new URLSearchParams(this.props.location.search)
    this.fetchProducts(query.get('search'));
  }

  fetchProducts(search) {
    if (!!search) {
      this.props.fetchSearchProducts(search);
    }
  }

  render() {
    const { items, working } = this.props;
    let { url } = this.props.match;

    return working
      ? <Loading />
      : (
        <div className="item-list-container p-1">
          {(items.length === 0)
            ? 'Bienvenido'
            : items.map((item) =>
              <Link key={item.id.toString()} to={`${url}/${item.id}`}>
                <div className="product-item">
                  <div className="product-item-img">
                    <figure>
                      <img
                        src={item.picture}
                        className="item-image"
                        alt={item.title} />
                    </figure>
                  </div>
                  <div className="product-item-info">
                    <div className="product-item-info-options location">{item.city_name}</div>
                    <div className="product-item-info-options amount">
                      <h2 className="price">
                        {/* {{ item.price.amount | currency:item.price.amount.currency }} */}
                        {currencyFormat(item.price.amount)}
                      </h2>
                      {item.free_shipping ? <DeliveryIcon /> : ''}
                    </div>
                    <div className="product-item-info-options">
                      <h3 className="m-0">{item.title}</h3>
                    </div>
                  </div>
                </div>
              </Link>)}
        </div>
      );
  }
}

function mapStateToProps(state) {
  return {
    items: selectItems(state),
    working: selectWorking(state)
  }
}

function mapDispatchToProps(dispatch) {
  return bindActionCreators({ fetchSearchProducts }, dispatch)
}

export default connect(mapStateToProps, mapDispatchToProps)(Itemlist)

// frontend/src/app/modules/items/components/item-list/item-list.component.ts
import { filter, tap } from 'rxjs/operators';
import { ItemsI } from './../../entities/items.entity';
import { Observable } from 'rxjs';
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ItemsFacade } from './../../items.facade';

@Component({
  selector: 'app-item-list',
  templateUrl: './item-list.component.html',
  styleUrls: ['./item-list.component.sass'],
})
export class ItemListComponent implements OnInit {
  constructor(private route: ActivatedRoute, private facade: ItemsFacade) {}

  ngOnInit(): void {
    this.route.queryParams
      .pipe(
        filter(({ search }) => !!search)
      )
      .subscribe(({ search }) => this.facade.fetchSearchProducts(search));
  }

  get items$(): Observable<ItemsI[]> {
    return this.facade.items$;
  }

  get working$(): Observable<boolean> {
    return this.facade.working$;
  }
}

<div class="item-list-container p-1">
    <ng-container *ngIf="(working$ | async); else ((items$ | async).length > 0) ? content : empty">
        <ng-container *ngFor="let item of [1,1,1,1]">
            <div class="card-loader card-loader-item-1"></div>
        </ng-container>
    </ng-container>
    <ng-template #content>
        <pre>
            {{  (items$ | async) | json }}
        </pre>
        <div
            *ngFor="let item of [1,1,1]"
            [routerLink]="['/items', 2]"
            class="product-item">
            <div class="product-item-img">
                <figure>
                    <img
                        src="https://http2.mlstatic.com/D_NQ_NP_805950-MCO40352919808_012020-O.webp"
                        class="item-image"
                        alt="Celular iPhone 11 128gb Nuevo 100% Original Y Sellada ">
                </figure>
            </div>
            <div class="product-item-info">
                <div class="product-item-info-options location">Bogotá</div>
                <div class="product-item-info-options amount">
                    <h2 class="price">$ 300.000</h2>
                    <span class="delivery-icon">
                        <img
                            src="./assets/img/track.svg"
                            alt="Envio">
                    </span>
                </div>
                <div class="product-item-info-options">
                    <h3 class="m-0">
                        Celular iPhone 11 128gb Nuevo 100% Original Y Sellada
                    </h3>
                </div>
                
            </div>
        </div>
    </ng-template>
    <ng-template #empty>
        Bienvenido
    </ng-template>
</div>
